In [22]:

import pandas as pd
import numpy as np

In [24]:
df=pd.read_csv('flood_risk_dataset_india.csv')

In [26]:
df.head()

,Latitude,Longitude,Rainfall (mm),Temperature (°C),Humidity (%),River Discharge (m³/s),Water Level (m),Elevation (m),Land Cover,Soil Type,Population Density,Infrastructure,Historical Floods,Flood Occurred
0,18.861663,78.835584,218.999493,34.144337,43.912963,4236.182888,7.415552,377.465433,Water Body,Clay,7276.742184,1,0,1
1,35.570715,77.654451,55.353599,28.778774,27.585422,2472.585219,8.811019,7330.608875,Forest,Peat,6897.736956,0,1,0
2,29.227824,73.108463,103.991908,43.934956,30.108738,977.328053,4.631799,2205.873488,Agricultural,Loam,4361.518494,1,1,1
3,25.361096,85.610733,198.984191,21.569354,34.453690,3683.208933,2.891787,2512.277800,Desert,Sandy,6163.069701,1,1,0
4,12.524541,81.822101,144.626803,32.635692,36.292267,2093.390678,3.188466,2001.818223,Agricultural,Loam,6167.964591,1,0,0

In [28]:
df.value_counts().sum()

np.int64(10000)

In [30]:
print(df.columns)

Index(['Latitude', 'Longitude', 'Rainfall (mm)', 'Temperature (°C)',
       'Humidity (%)', 'River Discharge (m³/s)', 'Water Level (m)',
       'Elevation (m)', 'Land Cover', 'Soil Type', 'Population Density',
       'Infrastructure', 'Historical Floods', 'Flood Occurred'],
      dtype='object')

In [35]:
df.drop(columns=['Latitude','Longitude','River Discharge (m³/s)','Land Cover','Soil Type','Water Level (m)','Elevation (m)','Population Density','Infrastructure','Historical Floods'], inplace=True)

In [36]:
df.head()

   Rainfall (mm)  Temperature (°C)  Humidity (%)  Flood Occurred
0     218.999493         34.144337     43.912963               1
1      55.353599         28.778774     27.585422               0
2     103.991908         43.934956     30.108738               1
3     198.984191         21.569354     34.453690               0
4     144.626803         32.635692     36.292267               0

In [49]:
(df['Rainfall (mm)']>124.5).sum()

np.int64(5844)

In [58]:
(df['Temperature (°C)']<20).sum()

np.int64(1666)

In [59]:
df_copy=df

In [62]:
arr=np.array(df_copy['Rainfall (mm)'])

In [ ]:
conditions = [
    (df["Rainfall (mm)"] < 7.6),
    (df["Rainfall (mm)"] >= 7.6) & (df["Rainfall (mm)"] < 35.5),
    (df["Rainfall (mm)"] >= 35.5) & (df["Rainfall (mm)"] < 64.5),
    (df["Rainfall (mm)"] >= 64.5) & (df["Rainfall (mm)"] < 124.4),
    (df["Rainfall (mm)"] >= 124.4)
]
choices = ["minimum risk", "low", "mild", "warning", "high"]
df["Risk"] = np.select(conditions, choices, default="unknown")

      Rainfall (mm)  Temperature (°C)  Humidity (%)  Flood Occurred  \
0        218.999493         34.144337     43.912963               1
1         55.353599         28.778774     27.585422               0
2        103.991908         43.934956     30.108738               1
3        198.984191         21.569354     34.453690               0
4        144.626803         32.635692     36.292267               0
...             ...               ...           ...             ...
9995     285.682635         37.621017     69.795616               0
9996     224.347263         37.935808     38.095486               0
9997       5.836759         23.087083     79.919607               1
9998     120.301453         28.029593     61.680873               1
9999      77.219394         29.622711     88.936537               1

              Risk
0             high
1             mild
2          warning
3             high
4             high
...            ...
9995          high
9996          high
9997  minimum risk
9998       warning
9999       warning

[10000 rows x 5 columns]

In [76]:
df["Risk"].value_counts()

Risk
high            5846
warning         2057
low              935
mild             923
minimum risk     239
Name: count, dtype: int64

In [93]:
df['Risk'] = pd.Categorical(df['Risk'], categories=choices,ordered=True)
df['Risk_encoded'] = df['Risk'].cat.codes

In [94]:
df.head()

,Rainfall (mm),Temperature (°C),Humidity (%),Flood Occurred,Risk,Risk_enc,Risk_encoded
0,218.999493,34.144337,43.912963,1,high,0,4
1,55.353599,28.778774,27.585422,0,mild,2,2
2,103.991908,43.934956,30.108738,1,warning,4,3
3,198.984191,21.569354,34.453690,0,high,0,4
4,144.626803,32.635692,36.292267,0,high,0,4

In [105]:
df.drop(columns=['Risk'],inplace=True)

In [96]:
df.head()

,Rainfall (mm),Temperature (°C),Humidity (%),Flood Occurred,Risk,Risk_encoded
0,218.999493,34.144337,43.912963,1,high,4
1,55.353599,28.778774,27.585422,0,mild,2
2,103.991908,43.934956,30.108738,1,warning,3
3,198.984191,21.569354,34.453690,0,high,4
4,144.626803,32.635692,36.292267,0,high,4

In [97]:
[df["Risk"].value_counts(),df['Risk_encoded'].value_counts()]

[Risk
 high            5846
 warning         2057
 low              935
 mild             923
 minimum risk     239
 Name: count, dtype: int64,
 Risk_encoded
 4    5846
 3    2057
 1     935
 2     923
 0     239
 Name: count, dtype: int64]

In [106]:
df.to_csv("flood.csv")